### ISSUE TITLE
Invalid syntax in run.py, line 31

### ISSUE THREAD

**Issue by mikelauff** [dylanjcastillo/stayhomeandlearn.org#1]
Hey! Nice project. I'm looking forward to getting it working. I've followed your instructions and had no issues until I go an try to run it locally. Here's my result...
```
python run.py            
  File "run.py", line 31
    print(f"### Deploy site: {args.environment} ###")
                                                   ^
SyntaxError: invalid syntax

```

**Comment by dylanjcastillo** [comment]
Thanks @mikelauff! It seems that you are not using the python interpreter from the virtual environment.

If you run `which python`, does it show something like `YOUR_REPOSITORY_DIRECTORY/venv/bin/python`?

If that is not the case then from the root folder of the repository run `source venv/bin/activate`. Then try again running `python run.py`.

I'm going to add this to the documentation. Thanks for raising it.

**Comment by mikelauff** [comment]
Thanks @dylanjcastillo! That resolved my issue. I can deploy locally now.
